using System.Collections.Generic;

namespace Hbm2Code.DomainModels
{
    public class Area : HasAutoGeneratedIdEntity
    {
        public Area()
        {
        }

        public virtual string Name { get; set; }

        public virtual ICollection<Agency> Agencies { get; protected set; }
    }
}