namespace Hbm2Code.DomainModels
{
    public class BaseObject : HasAutoGeneratedIdEntity
    {
        public virtual string Name { get; set; }

        public virtual long Version { get; protected set; }
    }
}