using System.Collections.Generic;

namespace Hbm2Code.DomainModels
{
    public class Category : HasAutoGeneratedIdEntity
    {
        public Category()
        {
        }

        public virtual string Name { get; set; }

        public ICollection<Item> Items { get; set; }
    }

    public class Item : HasAutoGeneratedIdEntity
    {
        public Item()
        {
        }

        public virtual string Name { get; set; }

        public IList<Category> Categories { get; set; }
    }
}