using System;

namespace Hbm2Code.DomainModels
{

    public abstract class Worker : HasAutoGeneratedIdEntity
    {
        public virtual string Name { get; set; }

    }

    public class ForeignWorker : Worker
    {
        public string PassportNo { get; set; }
    }

    public class DomesticWorker : Worker
    {
        public string SocialSecurityNo { get; set; }
    }
}
